object Libs {
    const val ANDROIDX_HILT_COMPILER = "androidx.hilt:hilt-compiler"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val APP_COMPAT = "androidx.appcompat:appcompat"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_VIEWMODEL = "androidx.hilt:hilt-lifecycle-viewmodel"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val HILT_TESTING = "com.google.dagger:hilt-android-testing"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val RETROFIT_CONVERTER = "com.github.akarnokd:rxjava3-retrofit-adapter"
    const val GSON_CONVERTER = "com.squareup.retrofit2:converter-gson"
    const val GSON = "com.google.code.gson:gson"
    const val MATERIAL = "com.google.android.material:material"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val RECYCLERVIEW = "androidx.recyclerview:recyclerview"
    const val SWIPE_REFRESH_LAYOUT = "androidx.swiperefreshlayout:swiperefreshlayout"
    const val RX_SWIPE_REFRESH_LAYOUT = "com.jakewharton.rxbinding4:rxbinding-swiperefreshlayout"
    const val RX_ANDROID = "io.reactivex.rxjava3:rxandroid"
    const val RX_JAVA = "io.reactivex.rxjava3:rxjava"
    const val RX_KOTLIN = "io.reactivex.rxjava3:rxkotlin"
    const val GLIDE = "com.github.bumptech.glide:glide"
    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx"
    const val LIFECYCLE_RUN_TIME = "androidx.lifecycle:lifecycle-runtime-ktx"
    const val OKHTTP = "com.squareup.okhttp3:okhttp"
    const val OKHTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor"
    const val OKHTTP_MOCK_SERVER = "com.squareup.okhttp3:mockwebserver"
    const val JUNIT = "junit:junit"
    const val JUNIT_EXT = "androidx.test.ext:junit"
    const val ESPRESSO = "androidx.test.espresso:espresso-core"
    const val TIMBER = "com.jakewharton.timber:timber"
    const val NAVIGATION_KTX = "androidx.navigation:navigation-fragment-ktx"
    const val NAVIGATION_UI = "androidx.navigation:navigation-ui-ktx"

}
